# # .pre-commit-config.yaml
# # ✅ Fully verified, production-ready config for React/Next.js projects
# # Runs ESLint, Prettier, Stylelint, Commitlint, and general hygiene checks

# repos:
#   # ✅ General Git hygiene hooks
#   - repo: https://github.com/pre-commit/pre-commit-hooks
#     rev: v4.5.0
#     hooks:
#       - id: trailing-whitespace
#       - id: end-of-file-fixer
#       - id: check-yaml
#       - id: check-json
#       - id: check-added-large-files

#   # ✅ Prettier (JavaScript, TypeScript, Markdown, JSON, YAML, etc.)
#   - repo: https://github.com/pre-commit/mirrors-prettier
#     rev: v3.2.5
#     hooks:
#       - id: prettier
#         additional_dependencies:
#           - prettier@3.2.5
#           - prettier-plugin-tailwindcss@0.5.7

#   # ✅ Commit message linting (via Husky + Commitlint)
#   - repo: local
#     hooks:
#       - id: commitlint
#         name: commitlint
#         entry: npx --no-install commitlint --edit $1
#         language: system
#         stages: [commit-msg]

#   # ✅ ESLint (JS/TS/React)
#   - repo: local
#     hooks:
#       - id: eslint
#         name: eslint
#         entry: npx --no-install eslint . --ext .ts,.tsx,.js,.jsx
#         language: system
#         types_or: [javascript, typescript]

#   # ✅ Stylelint (SCSS/CSS/Tailwind)
#   - repo: local
#     hooks:
#       - id: stylelint
#         name: stylelint
#         entry: npx --no-install stylelint "**/*.{css,scss,sass,tsx}"
#         language: system
#         types: [file]

#   # ✅ TypeScript type check
#   - repo: local
#     hooks:
#       - id: typecheck
#         name: tsc
#         entry: npx --no-install tsc --noEmit
#         language: system
#         pass_filenames: false

#   - repo: https://github.com/zricethezav/gitleaks
#     rev: v8.18.1
#     hooks:
#       - id: gitleaks
# ✅ Fully verified, production-ready config for React/Next.js projects
# Runs ESLint, Prettier, Stylelint, Commitlint, Type Check, and Secret Scanning

repos:
  # ✅ Git hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  # ✅ Prettier (JS/TS/MD/JSON/YAML/Tailwind formatting)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-tailwindcss@0.5.7
        pass_filenames: true

  # ✅ Commit message linting via Husky + Commitlint
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: npx --no-install commitlint --edit $1
        language: system
        stages: [commit-msg]

  # ✅ ESLint (JS/TS/React + Next.js)
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx --no-install eslint . --ext .ts,.tsx,.js,.jsx
        language: system
        pass_filenames: false

  # ✅ Stylelint (CSS/SCSS/Tailwind)
  - repo: local
    hooks:
      - id: stylelint
        name: stylelint
        entry: npx --no-install stylelint "**/*.{css,scss,sass,tsx}"
        language: system
        pass_filenames: false

  # ✅ TypeScript Type Check
  - repo: local
    hooks:
      - id: typecheck
        name: tsc
        entry: npx --no-install tsc --noEmit
        language: system
        pass_filenames: false

  # ✅ Secret scanning (highly recommended)
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        exclude: ^(node_modules|public)/
