repos:
  # Prettier for code formatting (JS/TS/JSON/Markdown/XML)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.8.8  # Latest 2.x version as of 2024, compatible with most projects
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.8
          - '@prettier/plugin-xml@0.16.0'

  # ESLint for JS/TS linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0  # Must match your local ESLint version
    hooks:
      - id: eslint
        entry: npx eslint .
        language: system
        types_or: [javascript, typescript]

  # Check for trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Optional: Detect merge conflict markers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: detect-merge-conflict
