---
version: '3.8'
services:
  stock-dashboard-ui:
    container_name: stock-dashboard-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports: [3000:3000]
    environment: [NODE_ENV=production]
    restart: unless-stopped
    networks: [frontend_network]
    healthcheck:
      test: [CMD, wget, --spider, -q, http://localhost:3000]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  frontend_network:
    name: frontend_network
    driver: bridge
