#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🔒 Running Gitleaks scan..."
gitleaks detect --no-git -v --redact || exit 1

echo "🔎 Verifying dependency licenses..."
npm run check:licenses || exit 1

npx lint-staged