name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd docs
          npm ci

      - name: Build Docusaurus site
        run: |
          cd docs
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd docs
          npx docusaurus deploy --skip-build
        env:
          GIT_USER: finsite
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
