name: Sign Docker Image and Attach SBOM

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write  # 🔐 Required for keyless signing
  contents: read
  packages: write

jobs:
  sign-and-attest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Generate SBOM
        run: |
          npm install -g @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-format json --output-file sbom.json

      - name: Attach SBOM to image
        run: |
          cosign attach sbom --sbom sbom.json ghcr.io/${{ github.repository }}:latest

      - name: Sign Docker image
        run: |
          cosign sign --yes ghcr.io/${{ github.repository }}:latest

      - name: Sign SBOM attestation
        run: |
          cosign attest --yes --type=sbom --predicate=sbom.json ghcr.io/${{ github.repository }}:latest
