name: Verify Docker Signature and SBOM

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Verify image signature
        run: |
          cosign verify ghcr.io/${{ github.repository }}:latest

      - name: Verify SBOM attestation
        run: |
          cosign verify-attestation \
            --type=sbom \
            ghcr.io/${{ github.repository }}:latest
